services:
#    ninfac_conta.example:
#        class: Ninfac\ContaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
    #MENU PARTIDAS CONTABLES
    ninfac_conta.admin.con_partidacontable:
        class: Ninfac\ContaBundle\Admin\ConPartidacontableAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\ConPartidacontable, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Contabilidad, label: Partidas contables }
        public: true

    ninfac_conta.admin.con_partidacontable_detalle:
        class: Ninfac\ContaBundle\Admin\ConPartidacontableDetalleAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\ConPartidacontableDetalle, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        public: true

    #MENU LISTAS ADMINISTRABLES
    ninfac_conta.admin.ctl_empresa:
        class: Ninfac\ContaBundle\Admin\CtlEmpresaAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlEmpresa, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Empresas }

    ninfac_conta.admin.ctl_anio:
        class: Ninfac\ContaBundle\Admin\CtlAnioAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlAnio, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Ejercicio contable }

    ninfac_conta.admin.ctl_periodocontable:
        class: Ninfac\ContaBundle\Admin\CtlPeriodocontableAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlPeriodocontable, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Periodo contable }

    ninfac_conta.admin.ctl_tipo_cuentacontable:
        class: Ninfac\ContaBundle\Admin\CtlTipoCuentacontableAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlTipoCuentacontable, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Tipo Cuenta contable }
        public: true

    ninfac_conta.admin.ctl_nivel_cuentacontable:
        class: Ninfac\ContaBundle\Admin\CtlNivelCuentacontableAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlNivelCuentacontable, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Nivel Cuenta contable }
        public: true

    ninfac_conta.admin.ctl_tipo_partida:
        class: Ninfac\ContaBundle\Admin\CtlTipoPartidaAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlTipoPartida, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Tipo partida }
        public: true

    ninfac_conta.admin.ctl_forma_partida:
        class: Ninfac\ContaBundle\Admin\CtlFormaPartidaAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlFormaPartida, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Forma partida }
        public: true


    #INVENTARIOS
    ninfac_conta.admin.ctl_marca_producto:
        class: Ninfac\ContaBundle\Admin\CtlMarcaProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlMarcaProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_grupo_producto:
        class: Ninfac\ContaBundle\Admin\CtlGrupoProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlGrupoProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Grupo de productos }
        public: true

    ninfac_conta.admin.ctl_subgrupo_producto:
        class: Ninfac\ContaBundle\Admin\CtlSubgrupoProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlSubgrupoProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, show_in_dashboard: false }
        public: true

    #MANTENIMIENTOS
    ninfac_conta.admin.mnt_cuentacontable:
        class: Ninfac\ContaBundle\Admin\MntCuentacontableAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\MntCuentacontable, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Mantenimientos, label: Catalogos de cuenta }
        public: true

    ninfac_conta.admin.mnt_producto:
        class: Ninfac\ContaBundle\Admin\MntProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\MntProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Mantenimientos, label: Productos }
        public: true

    ninfac_conta.admin.ctl_editorial_producto:
        class: Ninfac\ContaBundle\Admin\CtlEditorialProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlEditorialProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_tipo_precio:
        class: Ninfac\ContaBundle\Admin\CtlTipoPrecioAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlTipoPrecio, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Tipo precio }
        public: true

    ninfac_conta.admin.mnt_precio_producto:
        class: Ninfac\ContaBundle\Admin\MntPrecioProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\MntPrecioProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_presentacion_producto:
        class: Ninfac\ContaBundle\Admin\CtlPresentacionProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlPresentacionProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, show_in_dashboard: false }
        public: true
