services:
#    ninfac_conta.example:
#        class: Ninfac\ContaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
    #MENU PARTIDAS CONTABLES
    ninfac_conta.admin.con_partidacontable:
        class: Ninfac\ContaBundle\Admin\ConPartidacontableAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\ConPartidacontable, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Contabilidad, label: Partidas contables }
        public: true

    ninfac_conta.admin.con_partidacontable_detalle:
        class: Ninfac\ContaBundle\Admin\ConPartidacontableDetalleAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\ConPartidacontableDetalle, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Contabilidad, label: Detalle de partida, show_in_dashboard: false }
        public: true

    #MENU LISTAS ADMINISTRABLES
    ninfac_conta.admin.ctl_empresa:
        class: Ninfac\ContaBundle\Admin\CtlEmpresaAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlEmpresa, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Empresas }

    ninfac_conta.admin.ctl_anio:
        class: Ninfac\ContaBundle\Admin\CtlAnioAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlAnio, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Ejercicio contable }

    ninfac_conta.admin.ctl_periodocontable:
        class: Ninfac\ContaBundle\Admin\CtlPeriodocontableAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlPeriodocontable, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Periodo contable }

    ninfac_conta.admin.ctl_tipo_cuentacontable:
        class: Ninfac\ContaBundle\Admin\CtlTipoCuentacontableAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlTipoCuentacontable, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Tipo Cuenta contable }
        public: true

    ninfac_conta.admin.ctl_nivel_cuentacontable:
        class: Ninfac\ContaBundle\Admin\CtlNivelCuentacontableAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlNivelCuentacontable, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Nivel Cuenta contable }
        public: true

    ninfac_conta.admin.ctl_tipo_partida:
        class: Ninfac\ContaBundle\Admin\CtlTipoPartidaAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlTipoPartida, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Tipo partida }
        public: true

    ninfac_conta.admin.ctl_forma_partida:
        class: Ninfac\ContaBundle\Admin\CtlFormaPartidaAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlFormaPartida, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Forma partida }
        public: true


    #INVENTARIOS
    ninfac_conta.admin.ctl_marca_producto:
        class: Ninfac\ContaBundle\Admin\CtlMarcaProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlMarcaProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Marca de producto, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_grupo_producto:
        class: Ninfac\ContaBundle\Admin\CtlGrupoProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlGrupoProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Grupo de productos }
        public: true

    ninfac_conta.admin.ctl_subgrupo_producto:
        class: Ninfac\ContaBundle\Admin\CtlSubgrupoProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlSubgrupoProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Subgrupo de producto, show_in_dashboard: false }
        public: true

    #MANTENIMIENTOS
    ninfac_conta.admin.mnt_cuentacontable:
        class: Ninfac\ContaBundle\Admin\MntCuentacontableAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\MntCuentacontable, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Mantenimientos, label: Catalogos de cuenta }
        public: true

    ninfac_conta.admin.mnt_producto:
        class: Ninfac\ContaBundle\Admin\MntProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\MntProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Mantenimientos, label: Productos }
        public: true

    ninfac_conta.admin.ctl_editorial_producto:
        class: Ninfac\ContaBundle\Admin\CtlEditorialProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlEditorialProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Editorial producto, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_tipo_precio:
        class: Ninfac\ContaBundle\Admin\CtlTipoPrecioAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlTipoPrecio, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Tipo precio }
        public: true

    ninfac_conta.admin.mnt_precio_producto:
        class: Ninfac\ContaBundle\Admin\MntPrecioProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\MntPrecioProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Inventario, label: Precio producto, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_presentacion_producto:
        class: Ninfac\ContaBundle\Admin\CtlPresentacionProductoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlPresentacionProducto, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Inventario, label: Presentacion producto, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_tipo_cliente:
        class: Ninfac\ContaBundle\Admin\CtlTipoClienteAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlTipoCliente, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Tipo cliente }
        public: true

    ninfac_conta.admin.ctl_tipo_documento:
        class: Ninfac\ContaBundle\Admin\CtlTipoDocumentoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlTipoDocumento, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Tipo documento, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.mnt_cliente:
        class: Ninfac\ContaBundle\Admin\MntClienteAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\MntCliente, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Mantenimientos, label: Clientes }
        public: true

    ninfac_conta.admin.ctl_tipo_movimiento:
        class: Ninfac\ContaBundle\Admin\CtlTipoMovimientoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlTipoMovimiento, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Tipo movimiento, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_motivo_movimiento:
        class: Ninfac\ContaBundle\Admin\CtlMotivoMovimientoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlMotivoMovimiento, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Motivo Movimiento }
        public: true

    ninfac_conta.admin.mnt_proveedor:
        class: Ninfac\ContaBundle\Admin\MntProveedorAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\MntProveedor, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Mantenimientos, label: Proveedores }
        public: true

    ninfac_conta.admin.inv_inventario:
        class: Ninfac\ContaBundle\Admin\InvInventarioAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\InvInventario, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Inventario, label: Inventarios }
        public: true

    ninfac_conta.admin.inv_inventario_detalle:
        class: Ninfac\ContaBundle\Admin\InvInventarioDetalleAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\InvInventarioDetalle, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Inventario, label: Detalle de inventario, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.mnt_empleado:
        class: Ninfac\ContaBundle\Admin\MntEmpleadoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\MntEmpleado, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Mantenimientos, label: Empleados }
        public: true

    ninfac_conta.admin.ctl_banco:
        class: Ninfac\ContaBundle\Admin\CtlBancoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlBanco, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Bancos }
        public: true

    ninfac_conta.admin.ctl_cargo:
        class: Ninfac\ContaBundle\Admin\CtlCargoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlCargo, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Cargo }
        public: true

    ninfac_conta.admin.ctl_sexo:
        class: Ninfac\ContaBundle\Admin\CtlSexoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlSexo, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Sexo, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_estadocivil:
        class: Ninfac\ContaBundle\Admin\CtlEstadocivilAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlEstadocivil, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Estado civil, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_oficina:
        class: Ninfac\ContaBundle\Admin\CtlOficinaAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlOficina, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm,  group: Listas maestras, label: Oficinas }
        public: true

    ninfac_conta.admin.ctl_tipocontrato:
        class: Ninfac\ContaBundle\Admin\CtlTipocontratoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlTipocontrato, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Tipo de contratos }
        public: true

    ninfac_conta.admin.ctl_nivelestudio:
        class: Ninfac\ContaBundle\Admin\CtlNivelestudioAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlNivelestudio, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Nivel de estudio, show_in_dashboard: false }
        public: true

    ninfac_conta.admin.ctl_centrotrabajo:
        class: Ninfac\ContaBundle\Admin\CtlCentrotrabajoAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlCentrotrabajo, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Listas maestras, label: Centro de trabajo }
        public: true
